ganjilgenap: ganjilgenap.o
	g++ ganjilgenap.o -o ganjilgenap

ganjilgenap.o: ganjilgenap.cpp
	g++ -c ganjilgenap.cpp -o ganjilgenap.o

test:  ganjilgenap
	 ./ganjilgenap	

clean:
	rm -f ganjilgenap.o ganjilgenap
